### ISSUE TITLE
[Q] Why use GCE + dispatch instead of cron?

### ISSUE THREAD

**Issue by CanadaHonk** [InternetUnexplorer/discord-overlay#8]
Why not just use cron with GH Actions? Just wondering, sorry for issue.

**Comment by InternetUnexplorer** [comment]
Thanks for asking! I initially was going to use cron for this, but I couldn't get it to run even hourly since cron actions get the lowest priority in scheduling as far as I can tell. And, since checking for updates should take less than a second anyway, going through a whole workflow (including cloning the repository every time) felt like a waste of resources, so instead of fighting with GitHub actions on the cron thing I ended up switching to sending a repository dispatch since it wasn't much harder.

The one downside is that it does make things way more complicated; I tried to document how it works but this is a good reminder for me to make the repository containing the NixOS configuration for the GCE instance public and clarify it all a bit more. I'll see if I can do that today. :)

**Comment by CanadaHonk** [comment]
Fair enough, interesting as GitHub say they support crons every >=5 mins lol. Thanks for the answer!

**Comment by InternetUnexplorer** [comment]
Yeah, I expected it to work too, but it didn't when I tried it for whatever reason. It took over an hour for the workflow to even run once. :(

Anyway, I [made the service configuration public](https://github.com/InternetUnexplorer/nixos-config-periapsis/blob/main/services/discord-overlay-updater.nix) and [documented the update process a bit more](./EXPLANATION.md) to hopefully make it clearer how everything works and why it works that way. :)
